"""initial schema

Revision ID: 7e90a0b187d2
Revises: 
Create Date: 2026-05-24 07:33:23.673340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e90a0b187d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eps_id'), 'eps', ['id'], unique=False)
    op.create_index(op.f('ix_eps_nombre'), 'eps', ['nombre'], unique=True)
    op.create_table('medicamentos_eps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('nombre_generico', sa.String(), nullable=True),
    sa.Column('nombre_comercial', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('diagnosticos_aplica', sa.JSON(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('eps_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eps_id'], ['eps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicamentos_eps_id'), 'medicamentos_eps', ['id'], unique=False)
    op.create_index(op.f('ix_medicamentos_eps_nombre'), 'medicamentos_eps', ['nombre'], unique=False)
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('eps_id', sa.Integer(), nullable=True),
    sa.Column('firma_path', sa.String(), nullable=True),
    sa.Column('firma_imagen', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['eps_id'], ['eps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicos_cedula'), 'medicos', ['cedula'], unique=True)
    op.create_index(op.f('ix_medicos_email'), 'medicos', ['email'], unique=False)
    op.create_index(op.f('ix_medicos_id'), 'medicos', ['id'], unique=False)
    op.create_index(op.f('ix_medicos_nombre'), 'medicos', ['nombre'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cedula', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.String(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('tipo_documento', sa.String(), nullable=True),
    sa.Column('tipo_paciente', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('eps_id', sa.Integer(), nullable=True),
    sa.Column('datos_incapacidad_json', sa.JSON(), nullable=True),
    sa.Column('radicaciones_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['eps_id'], ['eps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cedula'), 'pacientes', ['cedula'], unique=True)
    op.create_index(op.f('ix_pacientes_email'), 'pacientes', ['email'], unique=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_nombre'), 'pacientes', ['nombre'], unique=False)
    op.create_table('citas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('fecha_hora', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_id'), 'citas', ['id'], unique=False)
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('transcripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['citas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultas_id'), 'consultas', ['id'], unique=False)
    op.create_table('historiales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=True),
    sa.Column('motivo_consulta', sa.Text(), nullable=True),
    sa.Column('sintomas', sa.Text(), nullable=True),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('plan_tratamiento', sa.Text(), nullable=True),
    sa.Column('medicamentos_sugeridos', sa.JSON(), nullable=True),
    sa.Column('confirmado_por_medico', sa.Boolean(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('incapacidad_pdf_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historiales_id'), 'historiales', ['id'], unique=False)
    op.create_table('incapacidad_radicacion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=True),
    sa.Column('paso_actual', sa.Integer(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('ocr_json', sa.JSON(), nullable=True),
    sa.Column('rethus_json', sa.JSON(), nullable=True),
    sa.Column('adres_json', sa.JSON(), nullable=True),
    sa.Column('reporte_json', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['historial_id'], ['historiales.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incapacidad_radicacion_jobs_estado'), 'incapacidad_radicacion_jobs', ['estado'], unique=False)
    op.create_index(op.f('ix_incapacidad_radicacion_jobs_historial_id'), 'incapacidad_radicacion_jobs', ['historial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incapacidad_radicacion_jobs_historial_id'), table_name='incapacidad_radicacion_jobs')
    op.drop_index(op.f('ix_incapacidad_radicacion_jobs_estado'), table_name='incapacidad_radicacion_jobs')
    op.drop_table('incapacidad_radicacion_jobs')
    op.drop_index(op.f('ix_historiales_id'), table_name='historiales')
    op.drop_table('historiales')
    op.drop_index(op.f('ix_consultas_id'), table_name='consultas')
    op.drop_table('consultas')
    op.drop_index(op.f('ix_citas_id'), table_name='citas')
    op.drop_table('citas')
    op.drop_index(op.f('ix_pacientes_nombre'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_email'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cedula'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_medicos_nombre'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_id'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_email'), table_name='medicos')
    op.drop_index(op.f('ix_medicos_cedula'), table_name='medicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_medicamentos_eps_nombre'), table_name='medicamentos_eps')
    op.drop_index(op.f('ix_medicamentos_eps_id'), table_name='medicamentos_eps')
    op.drop_table('medicamentos_eps')
    op.drop_index(op.f('ix_eps_nombre'), table_name='eps')
    op.drop_index(op.f('ix_eps_id'), table_name='eps')
    op.drop_table('eps')
    # ### end Alembic commands ###
